### ISSUE TITLE
Extra observations erased by wrappers

### ISSUE THREAD

**Issue by howardh** [Farama-Foundation/gym-minigrid#181]
I've created a custom Minigrid environment that returns additional information in the observation, but those get removed when they pass through the observation wrappers. Is this intentional behaviour (i.e. should I not be adding extra info this way)? Or can the wrappers be modified to handle this scenario?

This should just be a simple change of the return statements from
```
        return {
            'mission': obs['mission'],
            'image': out
        }
```
to
```
        return {
            **obs,
            'image': out
        }
```

**Comment by maximecb** [comment]
Open to accepting this fix if you're willing to test it out and open a pull request 👍

**Comment by howardh** [comment]
What's your usual procedure for testing? I see you have a `run_tests.py` script, but I don't see a nice way to fit this in there. Would you be open to switching the testing setup to something like pytest?

**Comment by maximecb** [comment]
Well there are some wrappers in `run_tests.py`. I would rather not introduce a new dependency.

**Comment by pseudo-rnd-thoughts** [comment]
Close by https://github.com/Farama-Foundation/gym-minigrid/pull/182
