### ISSUE TITLE
[Bug Report] README seems out of sync

### ISSUE THREAD

**Issue by ArturNiederfahrenhorst** [Farama-Foundation/gym-minigrid#215]
If you are submitting a bug report, please fill in the following details and use the tag [bug].

**Describe the bug**

Not an actual bug, but I believe your current readme is out of sync with the state of the code.

Screenshot from your readme:
<img width="864" alt="Screenshot 2022-08-11 at 11 27 36" src="https://user-images.githubusercontent.com/9356806/184103999-c86b2f32-732c-4781-b70d-f2c04df8d47a.png">

Screenshot from me trying to play with wrappers:
<img width="534" alt="Screenshot 2022-08-10 at 23 27 08" src="https://user-images.githubusercontent.com/9356806/184023391-1ba0dc06-81db-4e57-b848-74e7bf7fa0e6.png">

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/gym-minigrid/issues) in the repo (**required**)

**Comment by pseudo-rnd-thoughts** [comment]
That is strange, I can't replicate your issue. 
Do you know what your minigrid version is ?
Have you updated to the latest version released yesterday?

**Comment by Dirichi** [comment]
I have the same issue. See this notebook to replicate it: https://colab.research.google.com/drive/1Sp_DWVPsdP5KgRSJJuoy-_iaDw9GlC4H#scrollTo=fQJjpJYypcDc

Version: gym-minigrid-1.1.0

**Comment by pseudo-rnd-thoughts** [comment]
Could you confirm that is the correct notebook. I have tested it and it raises no error
I have added a line `wrappers = gym_minigrid.wrappers` and no error is raised

**Comment by Dirichi** [comment]
Oops I mistakenly kept on editing that notebook after sharing it here.

This is a new notebook with the same test: https://colab.research.google.com/drive/15gt5i7AKAU0HevQsCQ4pxyksXsnovDaO#scrollTo=fQJjpJYypcDc

Looks like it works now, not sure what changed. However, I'm still getting the same error in a separate Kaggle notebook. The same version of grid is being downloaded.

https://www.kaggle.com/code/dirichi/muzero-uncertain

**Comment by rodrigodelazcano** [comment]
@Dirichi  and @ArturNiederfahrenhorst  can you check if it works now with the latest commit.

**Comment by ArturNiederfahrenhorst** [comment]
Not sure why this is the case though. Install from master with the referenced fix goes well but if I dir(), I don't get what I'd expect from the changed your made. Maybe @Dirichi experiences something else here.

<img width="1502" alt="Screenshot 2022-08-22 at 06 19 39" src="https://user-images.githubusercontent.com/9356806/185931172-38d18fa5-9566-41ad-b601-4bff51ff463d.png">

**Comment by rodrigodelazcano** [comment]
> Not sure why this is the case though. Install from master with the referenced fix goes well but if I dir(), I don't get what I'd expect from the changed your made. Maybe @Dirichi experiences something else here.
> 
> <img alt="Screenshot 2022-08-22 at 06 19 39" width="1502" src="https://user-images.githubusercontent.com/9356806/185931172-38d18fa5-9566-41ad-b601-4bff51ff463d.png">

I'm not able to replicate that same issue. I get the `wrappers` property when using`dir()`. How are you installing `gym_minigrid`.

Installing from source and pip worked for me:

`pip install git+https://github.com/Farama-Foundation/gym-minigrid.git@e85614b21061cd6713e2b2c4685a860b279090ca`
